name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: [ "Dockerfile", "docker-entrypoint-initdb.d/*.sql" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "Dockerfile", "docker-entrypoint-initdb.d/*.sql" ]

jobs:
  build:
    if: github.repository == 'mjavadhpour/mjhpour-postgres-hero'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_REPOSITORY }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag mjhpour/postgres-hero:dev \
          --label "org.opencontainers.image.created=$(date)" \
          --label "org.opencontainers.image.authors=@mjavadhpour" \
          --label "org.opencontainers.image.url=https://hub.docker.com/r/mjhpour/postgres-hero" \
          --label "org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/blob/main/README.md" \
          --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
          --label "org.opencontainers.image.version=dev" \
          --label "org.opencontainers.image.title=Postgres Hero"
        docker push mjhpour/postgres-hero:dev
