name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_REPOSITORY }}
        DOCKER_PASS: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |
        docker login -u $SUPER_SECRET -p $DOCKER_PASS
        docker build . --file Dockerfile --tag mjhpour/postgres-hero:dev
        docker push mjhpour/postgres-hero:dev
